### PR TITLE
feat: Gateway API

### LINKED ISSUE #55: Feature: Gateway API (v24.1)
### Link to API

https://docs.opnsense.org/development/api/core/routing.html

### Description

Could be useful

### PR DESCRIPTION
**Pull request by kdhlab**
Fixes: https://github.com/ansibleguy/collection_opnsense/issues/55 Started to work on this since it is useful for me. Haven't tested yet.

### CODE REVIEW

**Comment by ansibleguy** [comment]
Greetings!

Nice to hear 👍🏼 
I've wanted to start with this for some time, but currently have got so much work.

Will check your PR the next days!

**Comment by kdhlab** [comment]
@ansibleguy Finally got back working on this. The base functionality is here, just need error checking, tests, and docs. Sorry for the delay.

**Comment by kdhlab** [comment]
Put the docs and tests in. Let me know if I missed anything.

**Comment by ansibleguy** [comment]
Sorry for the delay. Will check it the next days!

**Comment by ansibleguy** [comment]
Alright - a summary of my changes:
- Renamed the module to `gateway` as `routing` is pretty generic.
- Merged the docs of `route` and `gateway`
- Renamed the module arguments to be snake-case (use underscores) as this is a the default of this collection
- Added some argument aliases for the lazy admins
- Fixes for the enabled-state
- Enabling tests after they worked

**Review by ansibleguy — APPROVED** [review]

**Pull request merged**
