### PR TITLE
Update shebangs to match developer guide

### PR DESCRIPTION
**Pull request by peteigel**
### Background

The Ansible developer guide give some [pretty specific advice](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#python-shebang-utf-8-coding) about the use shebangs in module files. 

> Begin your Ansible module with #!/usr/bin/python - this “shebang” allows ansible_python_interpreter to work.
> [ ... ]
> Using #!/usr/bin/env, makes env the interpreter and bypasses ansible_<interpreter>_interpreter logic.

This actually ended up causing issues for me, possibly because I run ansible in a virtual environment. The error I was getting was something like `/usr/bin/env python3: file or directory not found` (I've lost it in my scrollback unfortunately.)

This guidance is a little counter-intuitive to me, I've always used `/usr/bin/env` to resolve interpreters properly, but it looks like ansible actually handles the shebang itself, instead of leaving it to the shell. 

### Change

- Update shebangs to `#!/usr/bin/python`
- Added the utf-8 coding comment, as recommended in the guide

### Test

I've been using several modules from the updated collection and haven't hit any issues

### CODE REVIEW

**Comment by superstes** [comment]
Greetings.

I have multiple setups where these modules work just fine in python venv.

`#!/usr/bin/env python3` will always use the currently active venv or fallback to the global interpreter if none is.

**Comment by ansibleguy** [comment]
Greetings.

I will not change this as it will break existing integrations.
Most integrations I see are activating the venv beforehand and then executing Ansible.
The `ansible_python_interpreter` would have to be configured by each user that uses a venv: https://github.com/ansible/ansible/issues/4083
This seem unintuitive to me.

**Comment by ansibleguy** [comment]
Related: https://github.com/ansibleguy/collection_opnsense/pull/5

**Comment by peteigel** [comment]
@ansibleguy I hate to be that guy, but I'd like to ask to reconsider this change. 

Using `/usr/bin/env` not only deviates from the guidance in the developer guide, but also from the de-facto standard format for modules. I've looked at several examples and they _all_ use `#!/usr/bin/python` as recommended in the developer guide.
- [`community.general`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/aerospike_migrations.py#L1)
- [`amazon.aws`](https://github.com/ansible-collections/amazon.aws/blob/main/plugins/modules/autoscaling_group.py#L1)
- [`kubernetes.core`](https://github.com/ansible-collections/kubernetes.core/blob/main/plugins/modules/helm.py#L1)
- [`ansible.windows`](https://github.com/ansible-collections/ansible.windows/blob/main/plugins/modules/win_acl.py#L1)

I don't see why interpreter resolution should be different for this collection compared to the most others.

To be clear, I haven't done anything to initialize `ansible_python_interpreter`. I believe it gets initialized to the interpreter running the playbook for `localhost`, and follows [interpreter discovery](https://docs.ansible.com/ansible/latest/reference_appendices/interpreter_discovery.html) otherwise. This [ansible issue](https://github.com/ansible/ansible/issues/82535) provides at least a little more discussion around the issues that come up with `/usr/bin/env`

I'm not sure what the context of #5 was, but I do think that change introduces a bug.  I'm not 100% sure why it's working for @superstes and not for me. The use of a venv was just an offhand guess.

I do understand where you are coming from, and I'd hate to break someone else's integration for the sake of my own. I can continue using my fork if needed. However, I do think this change is better for the community at large. 

PS: Thanks a ton for the work you've put into this collection!

**Comment by superstes** [comment]
Greetings.

Will test it once I find time.
Currently I'm pretty busy 🫣

**Comment by germebl** [comment]
Same issue here - using a venv for ansible (with pipx) and when trying to run a alias task, getting the following error:

```
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: 1: /usr/bin/env python3: not found\n", "module_stdout": "", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}
```

Already have set in the ansible.cfg:
```
interpreter_python = /root/.local/pipx/venvs/ansible/bin/python3
```

But issue still persists - so changed interpreter does not get used.

So i changed with this command:
```
find "galaxy/ansibleguy/" -type f -exec sed -i 's|#!/usr/bin/env python3|#!/usr/bin/python|g' {} +
```

all occurrences of `#!/usr/bin/env python3` to `#!/usr/bin/python` and everything works fine.

**Comment by lexxxel** [comment]
same error:
```
module_stderr: |-
    /bin/sh: line 1: /usr/bin/env python3: No such file or directory
  module_stdout: ''
  msg: |-
    The module failed to execute correctly, you probably need to set the interpreter.
    See stdout/stderr for the exact error
  rc: 127
```

**Comment by ansibleguy** [comment]
Thanks for the responses 👍🏼 
Is now fixed on latest

**Comment by peteigel** [comment]
@ansibleguy thanks for taking care of this!

**Pull request closed without merging**
