### PR TITLE
Added action group

### PR DESCRIPTION
**Pull request by Low-Frequency**
Added action group to be abe to set default values for the whole collection without redundant code.

This would set the default values globally for all modules:
```yaml
---
- module_defaults:
    group/ansibleguy.opnsense.opnsense:
      firewall: "fw.example.com"
      ssl_verify: false
      api_key: "{{ lookup('ansible.builtin.env', 'OPNSENSE_KEY') }}"
      api_secret: "{{ lookup('ansible.builtin.env', 'OPNSENSE_SECRET') }}"
```

It's possible to add more groups, for example an `alias` group containing `alias`, `alias_multi` and `alias_purge` to set defaults only for a specific subset of modules. However I couldn't figure out how to nest groups so there wouldn't be redundant listing of the modules.
The syntax for defaults is: `group/namespace.collection.action_group`, so for the mentioned additional group it would be `group/ansibleguy.opnsense.alias`

### CODE REVIEW

**Comment by ansibleguy** [comment]
Hi.

Nice catch! :D
I'll dig deeper to find how to implement this!

\- AnsibleGuy

**Comment by Low-Frequency** [comment]
Thanks :)
It was more of a coincidence that I found this functionality, but a welcome one.

There is a section that should do this from my understanding, but I couldn't get it to work in my tests:
```yaml
action_groups:
  groupname:
    - metadata:
        extend_group:
          - another_group
```

**Comment by Low-Frequency** [comment]
I managed to nest the groups now. The naming of `extend_group` is a bit misleading. It expands the groups listed in the group it's defined in, not the other way round.

**Comment by ansibleguy** [comment]
Seems legit (:

**Pull request merged**
