### PR TITLE
Adding general option for API retries

### PR DESCRIPTION
**Pull request by ohartl**
The OPNsense API can be a little bit annoying from time to time. I regularly experience connect errors, either `httpx.ConnectError` or `httpx.ConnectTimeout` to the OPNsense API, which makes the playbook stop with an exception (example below)

Solutions
* use [ansible retry](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html#retrying-a-task-until-a-condition-is-met) on every task calling the API (which is annoying on the user side of this collection).
* or implement a retry mechanism on those connect errors, which httpx can do with a custom transport (as the pull request does). 
  See https://www.python-httpx.org/advanced/#custom-transports
  > Connection retries are also available via this interface. Requests will be retried the given number of times in case an httpx.ConnectError or an httpx.ConnectTimeout occurs, allowing smoother operation under flaky networks. 

Discussion points:
* I choose a default for `api_retries` of `3`, which can be discussed.
* I didn't really find a way to write a test. Do you have any ideas on that?
* Am I missing something?

Example of the error:
```
TASK [opnsense-wireguard-network : Adding firewall rules for WireGuard network] ****************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ConnectionError: Unable to connect 'GET => https://192.168.0.1/api/firewall/filter/get'!
failed: [192.168.0.1] (item={'description': 'wan_wireguard_netcup_ipv4', 'interface': 'wan', 'ip_protocol': 'inet', 'destination_net': 'wanip', 'destination_port': 51111, 'protocol': 'UDP'}) => changed=false 
  ansible_loop_var: rule
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/ansible/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
        yield
      File "/home/ansible/.local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 168, in start_tls
        raise exc
      File "/home/ansible/.local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 163, in start_tls
        sock = ssl_context.wrap_socket(
      File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
        return self.sslsocket_class._create(
      File "/usr/lib/python3.10/ssl.py", line 1100, in _create
        self.do_handshake()
      File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
        self._sslobj.do_handshake()
    ConnectionResetError: [Errno 104] Connection reset by peer
  
    The above exception was the direct cause of the following exception:
  
    Traceback (most recent call last):
      File "/home/ansible/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
        yield
      File "/home/ansible/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 228, in handle_request
        resp = self._pool.handle_request(req)
      File "/home/ansible/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
        raise exc
      File "/home/ansible/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
        response = connection.handle_request(request)
      File "/home/ansible/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
        raise exc
      File "/home/ansible/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
        stream = self._connect(request)
      File "/home/ansible/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 156, in _connect
        stream = stream.start_tls(**kwargs)
      File "/home/ansible/.local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 152, in start_tls
        with map_exceptions(exc_map):
      File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
        self.gen.throw(typ, value, traceback)
      File "/home/ansible/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
        raise to_exc(exc) from exc
    httpcore.ConnectError: [Errno 104] Connection reset by peer
  
    The above exception was the direct cause of the following exception:
  
    Traceback (most recent call last):
      File "/tmp/ansible_ansibleguy.opnsense.rule_payload_e06dgi7i/ansible_ansibleguy.opnsense.rule_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/module_utils/base/api.py", line 50, in get
      File "/home/ansible/.local/lib/python3.10/site-packages/httpx/_client.py", line 1041, in get
        return self.request(
      File "/home/ansible/.local/lib/python3.10/site-packages/httpx/_client.py", line 814, in request
        return self.send(request, auth=auth, follow_redirects=follow_redirects)
      File "/home/ansible/.local/lib/python3.10/site-packages/httpx/_client.py", line 901, in send
        response = self._send_handling_auth(
      File "/home/ansible/.local/lib/python3.10/site-packages/httpx/_client.py", line 929, in _send_handling_auth
        response = self._send_handling_redirects(
      File "/home/ansible/.local/lib/python3.10/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
        response = self._send_single_request(request)
      File "/home/ansible/.local/lib/python3.10/site-packages/httpx/_client.py", line 1002, in _send_single_request
        response = transport.handle_request(request)
      File "/home/ansible/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 227, in handle_request
        with map_httpcore_exceptions():
      File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
        self.gen.throw(typ, value, traceback)
      File "/home/ansible/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
        raise mapped_exc(message) from exc
    httpx.ConnectError: [Errno 104] Connection reset by peer
  
    During handling of the above exception, another exception occurred:
  
    Traceback (most recent call last):
      File "/home/ansible/.ansible/tmp/ansible-tmp-1703712110.4833777-35213-213337067714811/AnsiballZ_rule.py", line 107, in <module>
        _ansiballz_main()
      File "/home/ansible/.ansible/tmp/ansible-tmp-1703712110.4833777-35213-213337067714811/AnsiballZ_rule.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/ansible/.ansible/tmp/ansible-tmp-1703712110.4833777-35213-213337067714811/AnsiballZ_rule.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.ansibleguy.opnsense.plugins.modules.rule', init_globals=dict(_module_fqn='ansible_collections.ansibleguy.opnsense.plugins.modules.rule', _modlib_path=modlib_path),
      File "/usr/lib/python3.10/runpy.py", line 224, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_ansibleguy.opnsense.rule_payload_e06dgi7i/ansible_ansibleguy.opnsense.rule_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/modules/rule.py", line 68, in <module>
      File "/tmp/ansible_ansibleguy.opnsense.rule_payload_e06dgi7i/ansible_ansibleguy.opnsense.rule_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/modules/rule.py", line 64, in main
      File "/tmp/ansible_ansibleguy.opnsense.rule_payload_e06dgi7i/ansible_ansibleguy.opnsense.rule_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/modules/rule.py", line 56, in run_module
      File "/tmp/ansible_ansibleguy.opnsense.rule_payload_e06dgi7i/ansible_ansibleguy.opnsense.rule_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/modules/rule.py", line 46, in process
      File "/tmp/ansible_ansibleguy.opnsense.rule_payload_e06dgi7i/ansible_ansibleguy.opnsense.rule_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/module_utils/main/rule.py", line 89, in check
      File "/tmp/ansible_ansibleguy.opnsense.rule_payload_e06dgi7i/ansible_ansibleguy.opnsense.rule_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/module_utils/base/base.py", line 124, in find
      File "/tmp/ansible_ansibleguy.opnsense.rule_payload_e06dgi7i/ansible_ansibleguy.opnsense.rule_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/module_utils/base/base.py", line 581, in _call_search
      File "/tmp/ansible_ansibleguy.opnsense.rule_payload_e06dgi7i/ansible_ansibleguy.opnsense.rule_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/module_utils/base/cls.py", line 33, in _search_call
      File "/tmp/ansible_ansibleguy.opnsense.rule_payload_e06dgi7i/ansible_ansibleguy.opnsense.rule_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/module_utils/base/base.py", line 74, in search
      File "/tmp/ansible_ansibleguy.opnsense.rule_payload_e06dgi7i/ansible_ansibleguy.opnsense.rule_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/module_utils/base/api.py", line 54, in get
    ConnectionError: Unable to connect 'GET => https://192.168.0.1/api/firewall/filter/get'!
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
  rule:
    description: wan_wireguard_netcup_ipv4
    destination_net: wanip
    destination_port: 51111
    interface: wan
    ip_protocol: inet
    protocol: UDP
```

### CODE REVIEW

**Comment by ansibleguy** [comment]
Greetings!

Basically I like the idea of retries on connection errors.

But as I thought about it - an issue came to my mind:
What happens if we send an action request (usually POST) and this request runs into a timeout.
Most times this happens, because the OPNSense box is still processing the action.. I am able to observe that behavior with the unbound (reload) API.
In that case we should never retry the action, as it might lead to unexpected results. (downtime because of multiple service restarts, ...)

We could implement our own retry-loop logic that is only applied when fetching information to get around this issue.

**Comment by ansibleguy** [comment]
Also: I could keep the retry-count low by default, as network-admins might want to known if there is a connectivity problem.
And the module-defaults can be easily increased by using:

```yaml
  module_defaults:
    group/ansibleguy.opnsense.all:
      retries: 1337
```

**Comment by ohartl** [comment]
Would have to check this, but as I understood, httpx retry is more like a "retry connection". 
(As encode/httpcore defines: `retries: The maximum number of retries when trying to establish a connection.`)

Both `httpx.ConnectError=Failed to establish a connection` or `httpx.ConnectTimeout=Timed out while connecting to the host.` are only triggered when the http connection could not be established. So no data was send yet.

> But as I thought about it - an issue came to my mind: What happens if we send an action request (usually POST) and this request runs into a timeout. Most times this happens, because the OPNSense box is still processing the action.. I am able to observe that behavior with the unbound (reload) API. In that case we should never retry the action, as it might lead to unexpected results. (downtime because of multiple service restarts, ...)

Calling it only `retries`, would IMO confuse people about what its actually doing. Better name might be `connection_retries`

**Comment by ohartl** [comment]
True. We might even put it to `0` then by default. 
Also write a section in the docs > Troubleshoot section to recommend playing around with the values if such errors accrue regularly and cannot be fixed (by network-admins) 

> Also: I could keep the retry-count low by default, as network-admins might want to known if there is a connectivity problem. And the module-defaults can be easily increased by using:

**Comment by ansibleguy** [comment]
> Calling it only retries, would IMO confuse people about what its actually doing. Better name might be connection_retries

As the connection/api timeout is currently also called `timeout` I though this might be more consistent.
But we can use parameter-aliases:

* api_timeout => timeout
* api_retries => connect_retries (?)

As you mentioned - we should think about the possibility, that in the future there might also be a 'module-level' retry.

**Comment by ansibleguy** [comment]
> We might even put it to 0 then by default.

Might be good, yes.

**Comment by ansibleguy** [comment]
> ...httpx retry is more like a "retry connection"

Yes - I checked the library code (httpx => [httpcore](https://github.com/encode/httpcore/blob/master/httpcore/_sync/connection.py#L110)) and it seems it really only retries on connect-errors (ConnectError, ConnectTimeout) as you mentioned.
So this should be fine..

**Comment by ohartl** [comment]
Sound great. I think this would more represent the logic behind those two. For backwards compatibility we might need to alias `timeout` to `api_timeout`  also then.

> > Calling it only retries, would IMO confuse people about what its actually doing. Better name might be connection_retries
> 
> As the connection/api timeout is currently also called `timeout` I though this might be more consistent. But we can use parameter-aliases:
> 
> * api_timeout => timeout
> * api_retries => connect_retries (?)
> 
> As you mentioned - we should think about the possibility, that in the future there might also be a 'module-level' retry.

**Comment by ohartl** [comment]
This was a rebase, sorry 😅

**Comment by ohartl** [comment]
The changes work great for me.

Renaming `timeout` to `api_timeout` might be confusing considering the docs, examples and tests still mention `timeout`. Whats your opinion on changing those?

But this should also give flexibility when some OPNsense API has a timeout parameter in the future :)

**Comment by ansibleguy** [comment]
> I didn't really find a way to write a test. Do you have any ideas on that?

I've added a Unit-Test workflow for such tests.
See: https://github.com/ansibleguy/collection_opnsense/blob/latest/plugins/module_utils/base/api_test.py
But I currently have no good idea on how to test the `retries`..

**Comment by ansibleguy** [comment]
> Renaming timeout to api_timeout might be confusing...

As both are working I would keep the references to `timeout` in the docs.
I might clean it up later on.

**Review by ansibleguy — APPROVED** [review]

**Pull request merged**
