### PR TITLE
Feature: Add Support for Firewall [Interface] Groups

### PR DESCRIPTION
**Pull request by jiuka**
### Link to API

https://docs.opnsense.org/development/api/core/firewall.html#id7

### Description

It would be nice to setup/manage the [[Interface] Groups](https://docs.opnsense.org/manual/firewall_groups.html) with Ansible

### CODE REVIEW

**Comment by jiuka** [comment]
What would the preferred name for this module be? To follow the example given by `rule` and `aliase` and `source_nat` it should be named `group`. However this would be a very generic term which could lead to collisions with system user groups. Any preferences?

**Comment by ansibleguy** [comment]
Nice :D

Have not even had time to look into the new firewall features. Will give it a look the next few days.

I would name it something like `rule_interface_group` and add an module-alias `rule_if_group` as the groups are only related to firewall-rules and group interfaces.

**Comment by ansibleguy** [comment]
Greetings!

Just looked into that OPNSense feature - very nice to have.

Fixes:
* The [docs-link in the first line](https://github.com/ansibleguy/collection_opnsense/pull/84/files#diff-2f2f0071c81f5bba569aa7c6e1049d9e3bfc1e17dac50ae942d1ab41a04697cbR1) of the docs should be unique. Maybe something like `rule_if_group`
* Is there a reason why you added the `device` [alias](https://github.com/ansibleguy/collection_opnsense/pull/84/files#diff-b5b4b2e7667888a8233bb0c7ab453005d9ddcda996e9afcc1791ff3226b5609cR31)? Did not find any reference to it.
* Please add the `ints` and `interfaces` aliases to the `members` [argument](https://github.com/ansibleguy/collection_opnsense/pull/84/files#diff-b5b4b2e7667888a8233bb0c7ab453005d9ddcda996e9afcc1791ff3226b5609cR36)
* Please add the `seq` alias to the `sequence` argument
* If the tests work - enable them by adding it to the [test.sh](https://github.com/ansibleguy/collection_opnsense/blob/latest/scripts/test.sh#L62)

**Comment by jiuka** [comment]
* The docs-link has been changed
* The `device` alias has been removed as it was a copy&past artifact
* Other argument aliases have been added.
* I now got the tests working and added it to the test.sh too.

**Comment by ansibleguy** [comment]
Looks good!

Seems we have a lint error and I can't push to your branch - please fix it so we can continue to merge:
`plugins/modules/list.py:26:0: C0301: Line too long (128/120) (line-too-long)`

**Comment by ansibleguy** [comment]
Found an issue with the test.
On the test-box the only the interfaces 'lan' and 'opt1' exist.

When changing the interface of test `opn_fail1` to some random name like `abc` and setting the other ones to `lan` they seem to work.
We had a similar problem with the [gateway tests](https://github.com/ansibleguy/collection_opnsense/blob/latest/tests/gateway.yml#L19) where we allowed for an override via env-vars in case some dev wants to run them manually.

**Comment by ansibleguy** [comment]
Will merge and fix it myself afterwards.

Thank you for your contribution!

**Review by ansibleguy — APPROVED** [review]

**Comment by ansibleguy** [comment]
FYI: https://github.com/ansibleguy/collection_opnsense/commit/ee015921ccb99f045444548ca35ef883004dc8d2

**Pull request merged**
